Add test for channels-api (#157)
* start of channel-api testing

* add more test coverage

* test websockets

* log errors properly

* finish test coverage

diff --git a/.github/workflows/build-oasis-api.yml b/.github/workflows/build-oasis-api.yml
--- a/.github/workflows/build-oasis-api.yml
+++ b/.github/workflows/build-oasis-api.yml
@@ -43,13 +43,34 @@ jobs:
         working-directory: ./packages/server/channels-api
         run: make generate
 
+      - name: Install
+        working-directory: ./packages/server/oasis-api
+        run: make install
+
       - name: Build
         working-directory: ./packages/server/oasis-api
         run: make build
 
       - name: Test
         working-directory: ./packages/server/oasis-api
-        run: make test
+        run: gotestsum --junitfile unit-tests.xml -- -coverprofile=cover.out ./...
+
+      - name: Test Report
+        uses: mikepenz/action-junit-report@v3
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          report_paths: packages/server/oasis-api/unit-tests.xml    # Path to test results
+          include_passed: true
+          annotate_only: true
+          detailed_summary: true
+
+      - name: Compute Code Coverage
+        working-directory: ./packages/server/oasis-api
+        run: | 
+             echo "## Code Coverage" >> $GITHUB_STEP_SUMMARY
+             echo "|Filename|Function|Coverage|" >> $GITHUB_STEP_SUMMARY
+             echo "|--------|--------|--------|" >> $GITHUB_STEP_SUMMARY
+             go tool cover -func=cover.out |sed -r  's/[[:space:]]+/|/g'|sed -r 's/$/|/g'|sed -r 's/^/|/g' >> $GITHUB_STEP_SUMMARY
 
   publish:
     name: publish image
